
title: My Resume
url: 'www.uroskete.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Uros Kete  ## put your name
title: 'MOTION GRAPHIC &amp; VIDEO DESIGNER'  ## your title
location: London , UK


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
